/** Rutas internas (alineadas con landingpage-inxora donde aplica) */
export const ROUTES = {
  home: "/",
  nosotros: "/nosotros",
  contacto: "/contacto",
  faq: "/faq",
  cotizaciones: "/cotizaciones",
  catalogo: "/catalogo",
  suministros: "/suministros",
  seguridad: "/seguridad",
  herramientas: "/herramientas",
  avisoLegal: "/aviso-legal",
  politicaPrivacidad: "/politica-de-privacidad",
  politicaCookies: "/politica-de-cookies",
  terminos: "/terminos-y-condiciones",
  acuerdoPiloto: "/acuerdo-de-usuario-piloto",
  envios: "/envios",
  devoluciones: "/devoluciones",
  libroReclamaciones: "/libro-de-reclamaciones",
  crearCuenta: "/crear-cuenta",
} as const;
